### NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

In [1]:
#Importing Numpy Library

import numpy as np

# Numpy Array

### What is an array?

An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type.

Numpy arrays essentially come in two categories: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but a matrix can still have only one row or one column).

In [2]:
#Creating an array

my_lst=[1,2,3,4,5]

In [3]:
arr=np.array(my_lst)

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
type(arr)

numpy.ndarray

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
#Multinested array

my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [9]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [10]:
#Checking the shape of the array

arr.shape

(3, 5)

# Built-in Numpy methods

In [11]:
np.arange(0,10)

#Returns evenly spaced values within a given interval

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,11,2)

# 2 refers to step which indicates the spacing between interval values

array([ 0,  2,  4,  6,  8, 10])

## Zeros and Ones

Generates arrays of zeros or ones.

In [13]:
np.zeros(2)

array([0., 0.])

In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones(3)

array([1., 1., 1.])

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Linspace

Linspace returns array of evenly spaced numbers over a specified interval.

In [17]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [18]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## Random

Creates an array of random values

### rand

Creates an array of the given shape and populate it with random samples from a uniform distribution over [0, 1)

In [19]:
np.random.rand(2)

array([0.48466829, 0.74391258])

In [20]:
np.random.rand(4,3)

array([[0.89140947, 0.59110557, 0.44745225],
       [0.61428864, 0.93383143, 0.869647  ],
       [0.75967359, 0.58949299, 0.71410134],
       [0.93025295, 0.58339795, 0.5707398 ]])

### randn

Returns a sample from the sample normal distribution.

In [21]:
np.random.randn(3)

array([-1.77920813, -0.62951932, -0.56989034])

In [22]:
np.random.randn(5,5)

array([[-0.79527487, -0.85961725,  0.01193676, -1.07709818,  0.92096789],
       [-1.06382819,  0.97143511,  1.04047034,  0.99048076, -0.61743937],
       [ 2.02313827,  0.56554161,  1.45415501,  1.1990977 , -0.22993196],
       [ 1.54419327, -0.35324318,  1.2938312 ,  0.39734454, -0.30519165],
       [ 0.66390791,  0.70804294,  1.3285922 , -0.98113571,  0.56981066]])

### randint

Returns random integers from the specified interval (low and high).

In [23]:
np.random.randint(1,100)

91

In [24]:
np.random.randint(1,100,10)

#10 refers to the size of the array

array([10,  3, 26, 28, 83, 45, 65, 73, 94, 82])

### Reshape

Returns an array containing the same data with a new shape.

In [25]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [26]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax.

In [27]:
ranarr

array([42, 17, 13, 37, 18, 14, 12, 49, 45, 42])

In [28]:
print(ranarr.min())
print(ranarr.max())
print(ranarr.argmin())
print(ranarr.argmax())

12
49
6
7


### Shape

Shape is an attribute of an array.

In [29]:
arr.shape

#vector

(25,)

In [30]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [31]:
arr.reshape(1,25).shape

(1, 25)

In [32]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

# Numpy INDEXING and SELECTION

In [33]:
#Creating sample array

arr = np.arange(0,11)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
#Get a value at an index

arr[8]

8

In [36]:
#Get values in a range

arr[1:5]

array([1, 2, 3, 4])

In [37]:
#Get values in a range
arr[0:7]

array([0, 1, 2, 3, 4, 5, 6])

## Indexing 2D array

In [38]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [39]:
#Indexing row

arr_2d[1]

array([20, 25, 30])

In [40]:
#Format is arr_2d[row][col] or arr_2d[row,col]
#Getting individual element value

arr_2d[1][0]

20

In [41]:
# Getting individual element value

arr_2d[1,0]

20

In [42]:
#2D array slicing

arr_2d[:2,1:] #Shape (2,2) from top right corner

array([[10, 15],
       [25, 30]])

In [43]:
#Shape bottom row

arr_2d[2]

array([35, 40, 45])

In [44]:
#Shape bottom row

arr_2d[2,:]

array([35, 40, 45])

## Selection

In [45]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [47]:
bool_arr = arr > 4

In [48]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [49]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [50]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# Numpy OPERATIONS

## Arithmetic operations

In [52]:
arr = np.arange(0,10)

In [53]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [55]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [56]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [57]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [58]:
#Taking Square Roots

np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [59]:
#Calcualting exponential (e^)

np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [60]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [61]:
np.log(arr)

D:\Ananconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])